<?php

return [
    ['GET', '/page-not-found', 'PageNotFoundController@index', 'PageNotFoundIndex'],
    ['GET', '/', 'StaticPageController@home', 'StaticPageHome'],
    ['GET', '/login', 'AuthenticationController@loginForm', 'AuthenticationLoginForm'],
    ['POST', '/login', 'AuthenticationController@loginValidate', 'AuthenticationLoginValidate'],
    ['POST', '/logout', 'AuthenticationController@logout', 'AuthenticationLogout'],
    ['GET', '/register', 'AuthenticationController@registerForm', 'AuthenticationRegisterForm'],
    ['POST', '/register', 'AuthenticationController@registerValidate', 'AuthenticationRegisterValidate'],
    ['GET', '/confirm-registration', 'AuthenticationController@registerConfirm', 'AuthenticationRegisterConfirm'],
    ['GET', '/activate-free-membership', 'AuthenticationController@registerActivate', 'AuthenticationRegisterActivate'],
    ['GET', '/thanks-for-registering', 'AuthenticationController@registerThanks', 'AuthenticationRegisterThanks'],
    ['GET', '/profile', 'AuthenticationController@profile', 'AuthenticationProfile'],
    ['GET', '/profile/edit', 'AuthenticationController@profileEdit', 'AuthenticationProfileEdit'],
    ['PATCH', '/profile/edit', 'AuthenticationController@profileUpdate', 'AuthenticationProfileUpdate'],
    ['GET', '/curriculum', 'CurriculaController@index', 'CurriculaIndex'],
    ['POST', '/curriculum', 'CurriculaController@create', 'CurriculaCreate'],
    ['GET', '/curriculum/new', 'CurriculaController@new', 'CurriculaNew'],
    ['GET', '/curriculum/[:slug]/edit', 'CurriculaController@edit', 'CurriculaEdit'],
    ['GET', '/curriculum/[:slug]', 'CurriculaController@show', 'CurriculaShow'],
    ['PATCH', '/curriculum/[:slug]', 'CurriculaController@update', 'CurriculaUpdate'],
    ['GET', '/topics', 'TopicsController@index', 'TopicsIndex'],
    ['POST', '/topics', 'TopicsController@create', 'TopicsCreate'],
    ['GET', '/topics/new', 'TopicsController@new', 'TopicsNew'],
    ['GET', '/topics/[:curriculumSlug]/[:topicSlug]', 'TopicsController@show', 'TopicsShow'],
    ['GET', '/topics/[:curriculumSlug]/[:topicSlug]/quiz', 'TopicsController@quiz', 'TopicsQuiz'],
    ['POST', '/topics/[:curriculumSlug]/[:topicSlug]/quiz/create', 'TopicsController@create_quiz', 'TopicsCreateQuiz'],
    ['GET', '/skills', 'SkillsController@index', 'SkillsIndex'],
    ['POST', '/skills', 'SkillsController@create', 'SkillsCreate'],
    ['GET', '/skills/new', 'SkillsController@new', 'SkillsNew'],
    ['GET', '/skills/[:curriculumSlug]/[:topicSlug]/[:skillSlug]', 'SkillsController@show', 'SkillsShow'],
    ['GET', '/skills/[:curriculumSlug]/[:topicSlug]/[:skillSlug]/quiz', 'SkillsController@quiz', 'SkillsQuiz'],
    ['GET', '/skills/[:curriculumSlug]/[:topicSlug]/[:skillSlug]/videos', 'SkillsController@videos', 'SkillsVideos'],
    ['GET', '/skills/[:curriculumSlug]/[:topicSlug]/[:skillSlug]/worked-solutions', 'SkillsController@worked_solutions', 'SkillsWorkedSolutions'],
    ['POST', '/skills/[:curriculumSlug]/[:topicSlug]/[:skillSlug]/quiz/create', 'SkillsController@create_quiz', 'SkillsCreateQuiz'],
    ['POST', '/skill-questions', 'SkillQuestionsController@create', 'SkillQuestionsCreate'],
    ['GET', '/skill-questions/new', 'SkillQuestionsController@new', 'SkillQuestionsNew'],
    ['POST', '/videos', 'VideosController@create', 'VideosCreate'],
    ['GET', '/videos/new', 'VideosController@new', 'VideosNew'],
    ['POST', '/worked-solutions', 'WorkedSolutionsController@create', 'WorkedSolutionsCreate'],
    ['GET', '/worked-solutions/new', 'WorkedSolutionsController@new', 'WorkedSolutionsNew'],
    ['GET', '/worked-solutions/fetch/[:skillId]', 'WorkedSolutionsController@fetch', 'WorkedSolutionsFetch'],
    ['GET', '/quizzes/questions/[:quizId]', 'QuizzesController@fetchQuiz', 'quizzesFetchQuiz'],
    ['POST', '/quizzes/questions/record', 'QuizzesController@recordResponse', 'quizzesRecordResponse'],
    ['POST', '/quizzes/questions/record-completion', 'QuizzesController@recordCompletion', 'quizzesRecordComplettion'],
];
